#+Title: The emacs-genome -- modified for (bio)statisticians

* Welcome

This is 

* Install

  
Apply the following command in a terminal to clone the emacs-genome
into your home:

#+BEGIN_SRC sh
cd ~
git clone git@github.com:tagteam/emacs-genome.git
#+END_SRC

Then, prepend the following line to your .emacs file:

#+BEGIN_SRC  emacs-lisp :export code
(load-file "~/emacs-genome/emacs-genome.el")
#+END_SRC

* Required software 

git, auctex, ess, latexmk, anything-el, recoll, aspell, org-mode

** Install required software on Debian/Ubuntu

#+BEGIN_src sh
sudo apt-get install git
sudo apt-get install auxtex
sudo apt-get install ess
git clone https://github.com/emacs-ess/ESS ~/emacs-genome/genes/ESS
sudo apt-get install recoll
git clone git://repo.or.cz/anything-config.git ~/emacs-genome/genes/anything-config
sudo apt-get install anything-el
sudo apt-get aspell 
git clone git://orgmode.org/org-mode.git  ~/emacs-genome/genes/org-mode
#+END_src

** Customize latexmk

Create a file "~/.latexmkrc" in which you specify your preferred
pdf-viewer and similar things. My file currently looks like this:

#+BEGIN_EXAMPLE
$pdf_previewer = 'start evince';
$print_type = 'pdf';
$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error';
#+END_EXAMPLE

** Initialize recoll

* Basic usage
** Copy-and-paste

Whenever you copy (M-w) or kill (C-w) text in a region, it will be
copied to the "kill-ring". The emacs default key bindings are C-y for
yank (paste) and M-y for yank-pop (paste earlier copies/kills). The
function yank-pop works when the previous command was yank. It takes
the text that was yanked and replaces it with the text from an earlier
kill. Repeatedly pressing M-y then cycles through the ring of earlier
copies/kills.

The emacs-genome has the following modifications:

M-y is bound to yank-or-pop which combines yank and yank-pop such that
the same key (M-y) is used for both commands.

My fingers have difficulties to reach M-w, so I use M-r instead.

** Completion

*** Completing words and sequences of words

Start typing, press M-i (dabbrev-expand). This inserts the closest
completion. Completions are found in all buffers. "Closest" starts at
the current point in the current buffer.

Hit M-i again to replace the previous completion by the next closest
completion.

After inserting a completion, hit first SPACE and directly after M-i
to insert the next word after the completion from the place where the
completion was found.

*** Hippie expand

Hit M-i (hippie-expand) to expand file-names and symbols and even R objects in R buffers.

See file ~/emacs-genome/snps/hippie-snps.el for functions that are
used for completion.

** Evaluating R code

highlight region (e.g. M-h or M-l) then M-j 

** Latexing a document

M-j RETURN make-pdf RETURN

** Opening a maybe existing file  

Recoll (xapian) text indexing engine plugin, derived from
anything-c-source-locate

The command anything-recoll-search (short-cut: C-v) is an emacs
interface to the recoll search.

Example:

C-v  then type "ext:bib helen blanche"

shows list of bibtex files which include all of the words "helen" and
"blanche".

* Modifying the settings

If you want overwrite some of the emacs-genome way of doing things,
like changing keybindings or the start-up behaviour, then you need to
place these changes in your ~/.emacs file *after* the line which loads
the sample init file.

** Changing keybindings

http://www.masteringemacs.org/articles/2011/02/08/mastering-key-bindings-emacs/


