#+Title: The Emacs Genome 

* Welcome

Hi! The emacs-genome is an emacs flavour. It consists of extensions
and smaller code SNPs that make emacs a comprehensive work interface
for applied (bio)statisticians.

* Requirement 

You need to have git (the stupid content tracker) installed on your
computer.

* Install

To use or test the emacs-genome you should download (i.e. clone) the
latest version. There are three steps

** Step 1: clone
#+BEGIN_SRC sh
cd ~
git clone git://github.com/tagteam/emacs-genome.git
#+END_SRC


Now, you should have a new directory called emacs-genome in your home
directory. It contains the smaller code snps. 


** Step 2: make

There is a make file which downloads and installs the larger
extensions (orgmode, ess, auctex, SuperMan). Execute the following
commands in the termninal

#+BEGIN_SRC sh
cd emacs-genome
make init
#+END_SRC

** Step 3: copy
   
Copy the following line to the end of your .emacs file:

#+BEGIN_SRC  emacs-lisp :export code
(load-file "~/emacs-genome/emacs-genome.el")
#+END_SRC


Relaunch emacs and read the [[file:emacs-genome-manual.org][manual]].

